### ISSUE TITLE
[FEATURE] adding formatting

### ISSUE THREAD

**Issue by illyrius666** [ventojs/vscode-vento#10]
i noticed since using the vento template support that my code doesnt format. i pressume this is not a feature yet.

**Comment by oscarotero** [comment]
It's possible to format .vto using dprint (https://vento.js.org/formatter/)

and .vto files will be supported by `deno fmt` command in the next version (https://github.com/denoland/deno/pull/25831).

If you want to keep your files with `.html` extension, you have to load instead of copy them, so they are processed by tailwind:

```js
site.loadAssets([".html"]); // load .html files as assets.
```

**Comment by illyrius666** [comment]
> It's possible to format .vto using dprint (https://vento.js.org/formatter/)
> 
> and .vto files will be supported by `deno fmt` command in the next version ([denoland/deno#25831](https://github.com/denoland/deno/pull/25831)).
 i will wait for this
> If you want to keep your files with `.html` extension, you have to load instead of copy them, so they are processed by tailwind:
 i like vento more haha
> ```js
> site.loadAssets([".html"]); // load .html files as assets.
> ```
thank you for the quick explanation, this "issue" can be closed.
